language: "en-US"
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  auto_review:
    enabled: true
tools:
  spellcheck:
    enabled: true
  markdownlint:
    enabled: true
  biome:
    enabled: true
  github-checks:
    enabled: true
    timeout_ms: 180000
  languagetool:
    enabled: true
    enabled_only: false
    level: default
  hadolint:
    enabled: true
  yamllint:
    enabled: true
  gitleaks:
    enabled: true
  eslint:
    enabled: true
  actionlint:
    enabled: true
  semgrep:
    enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: "local"
  issues:
    scope: "local"
  pull_requests:
    scope: "local"
