# Development Docker file
FROM node:18-alpine

WORKDIR /async

# Install development dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port for development (if needed)
EXPOSE 3000

# Set environment variables for development
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]

# Build command -> docker build -f Dockerfile.dev --build-arg NODE_ENV=development -t app-dev .
