services:
  website:
    container_name: asyncapi-website
    image: asyncapi-website
    build: .
    pull_policy: build
    ports:
      - 3000:3000
    develop:
      watch:
        - path: .
          target: /async
          action: sync
        - path: package.json
          action: rebuild


