- companyName: Reiffeisen Bank
  useCase: Implementing a Continuous Integration and Continuous Delivery (CI/CD) pipeline utilizing GitOps principles to deploy a topology constructed on AsyncAPI definitions using a Kubernetes operator to an Apache Pulsar cluster.
  resources:
    - title: "Video: From an AsyncAPI Definition to a Deployed Pulsar Topology Via GitOps"
      link: https://www.youtube.com/watch?v=_MwzLZMwFN8

- companyName: LEGO Group
  useCase: Managing brokers, where developers abstain from direct access to the management console and instead upload AsyncAPI documents to a self-service API, which provisions access and topics specified in the documents.
  resources:
    - title: "Video: Documentation as Configuration for Management of Apache Pulsar"
      link: https://www.youtube.com/watch?v=m8I0fYjx6Cc

- companyName: LEGO Group
  useCase: Defining, documenting, and distributing event-driven APIs while ensuring consistency and governance.
  resources:
    - title: "Video: Cross-Domain Events with AsyncAPI and AWS"
      link: https://www.youtube.com/watch?v=qjarcJQVLOg

- companyName: Bank of New Zealand
  useCase: Establishing a decentralized company-wide governance strategy for APIs, providing a self-service platform for publishing APIs and documentation.
  resources:
    - title: "Video: Self-service Events & Decentralised Governance with AsyncAPI: A Real World Example"
      link: https://www.confluent.io/events/kafka-summit-apac-2021/self-service-events-and-decentralised-governance-with-asyncapi-a-real-world/

- companyName: Zora Robotics
  useCase: Documenting public MQTT APIs for IoT products and constructing a developer portal.
  resources:
    - title: "Video: Building and managing an extensive API for Robotics and IoT"
      link: https://www.youtube.com/watch?v=yjHgT0n2BtA
    - title: "Docs: Building and managing an extensive API for Robotics and IoT"
      link: https://docs.zorabots.be/dev-mqtt-docs/latest/index.html

- companyName: Walmart
  useCase: Managing a centralized API Hub for internal teams, enhancing event discoverability and visibility using AsyncAPI. AsyncAPI facilitates company-wide governance on asynchronous APIs.
  resources:
    - title: "Video: Time For AsyncAPI Specification"
      link: https://www.youtube.com/watch?v=SxTpGRaNIPo

- companyName: eBay
  useCase: Facilitating partner integration with eBay through asynchronous communication, leveraging public AsyncAPI documents for code generation and rapid integration, while ensuring governance and standardization.
  resources:
    - title: "Video: AsyncAPI 2.0: Enabling the Event-Driven World"
      link: https://www.youtube.com/watch?v=SxTpGRaNIPo
    - title: "Article: AsyncAPI 2.0: Enabling the Event-Driven World"
      link: https://innovation.ebayinc.com/tech/engineering/asyncapi-2-0-enabling-the-event-driven-world/
    - title: "Docs: Overview of Notification API with public AsyncAPI documents"
      link: https://developer.ebay.com/api-docs/commerce/notification/overview.html

- companyName: Postman
  useCase: Enhancing discoverability of information about system events by building a tool called Synapse for provisioning entire event-based infrastructure, with AsyncAPI documents as the source of truth.
  resources:
    - title: "Video: Turbocharging your Developer Ecosystem with Events Powered by SNS/SQS, Serverless, and AsyncAPI"
      link: https://www.youtube.com/watch?v=0_7QZyKLPoE

- companyName: Adobe
  useCase: Providing event documentation to expedite development by generating classes based on message payload information from AsyncAPI documents.
  resources:
    - title: "Slides: AsyncAPI and Modelina"
      link: https://drive.google.com/file/d/1AVCG9_fFtuOtrvZVZWENmU2aDT7C51Jr/view?usp=sharing

- companyName: Open University of Catalonia and Prodevelop
  useCase: Enabling monitoring of ports through a design-first approach, utilizing UML class diagrams to design the entire infrastructure. UML diagrams are source of truth for generated AsyncAPI documents that later are used for models and clients generation. These documents are extended with additional SLA properties to specify runtime quality of service requirements, facilitating real-time monitoring.
  resources:
    - title: "Video: Leveraging AsyncAPI To Detect Anomalies in Smart Ports Platforms"
      link: https://www.youtube.com/watch?v=m4KS6FSeTT4

- companyName: Oracle
  useCase: Documenting data streaming APIs with AsyncAPI documents for client library generation in various programming languages, reducing development time for applications consuming data.
  resources:
    - title: "Video: Productizing AsyncAPI for Data Replication"
      link: https://www.youtube.com/watch?v=CGLlxYy66LY

- companyName: TransferGo
  useCase: Enhancing discoverability of information about event-driven systems by documenting services with AsyncAPI, rendering documentation, and creating catalogs of events. Legacy services utilize a special library to generate AsyncAPI documents, while new services require AsyncAPI documents for generating PHP classes.
  resources:
    - title: "Slides: How TransferGo Uses AsyncAPI To Improve Developer Experience"
      link: https://drive.google.com/file/d/1t7tYMr8FMRInaZV0lWod1QfDuhhSjwBJ/view?usp=sharing

- companyName: Kuehne+Nagel
  useCase: Implementing a GitOps-based pipeline to enable self-service management of Kafka infrastructure, including access control management. Automation of AsyncAPI document governance ensures consistency in the infrastructure at the pull request level.
  resources:
    - title: "Slides: AsyncAPI For Platform Self-Service: A GitOps Tale"
      link: https://drive.google.com/file/d/1y67PI8NaITPPwZAiDF2Zs7ISfcIpqMV8/view?usp=sharing

- companyName: Adidas
  useCase: AsyncAPI is a standard for defining asynchronous APIs using Apache Kafka. AsyncAPI governed under official guidelines. AsyncAPI is promoted to be used for documentation and code generation.
  resources:
    - title: "Docs: AsyncAPI and Kafka Guidelines"
      link: https://adidas.gitbook.io/api-guidelines/asynchronous-api-guidelines/kafka-asynchronous-guidelines/a_introduction/why-asyncapi

- companyName: Morgan Stanley
  useCase: AsyncAPI is promoted not only inside the company but also as a standard for FinOS Foundation for managing architecture as code.
  resources:
    - title: "Slides: Deploying WebSockets with AsyncAPI and Architecture as Code"
      link: https://drive.google.com/file/d/1YzLwQZsMUXGwj_Lsqv-ZnvV2knuowWrS/view?usp=drive_link
