- companyName: Reiffeisen Bank
  useCase: Continuous Integration and Continuous Delivery (CI/CD) pipeline based on GitOps to deploy a topology built on Async API definitions using a Kubernetes operator to an Apache Pulsar cluster.
  resources:
    - title: Video - From an AsyncAPI Definition to a Deployed Pulsar Topology Via GitOps
      link: https://www.youtube.com/watch?v=_MwzLZMwFN8

- companyName: LEGO Group
  useCase: Broker management, where developers do not access the management console themselves, but rely on uploading AsyncAPI documents to a self service API that provisions access and topics specified in documents.
  resources:
    - title: Video - Documentation as Configuration for Management of Apache Pulsar
      link: https://www.youtube.com/watch?v=m8I0fYjx6Cc

- companyName: LEGO Group
  useCase: Define, document and distribute event-driven APIs. Ensuring consistency and governance
  resources:
    - title: Video - Cross-Domain Events with AsyncAPI and AWS
      link: https://www.youtube.com/watch?v=qjarcJQVLOg

- companyName: Bank of New Zealand
  useCase: Decentralized company-wide governance strategy for API. A self service for publishing APIs and docs.
  resources:
    - title: "Video - Self-service Events & Decentralised Governance with AsyncAPI: A Real World Example"
      link: https://www.confluent.io/events/kafka-summit-apac-2021/self-service-events-and-decentralised-governance-with-asyncapi-a-real-world/

- companyName: Zora Robotics
  useCase: Documenting lot products public MQTT API and building a developers portal.
  resources:
    - title: Video - Buliding and managing an extensive API for Robotics and loT
      link: https://www.youtube.com/watch?v=yjHgT0n2BtA
    - title: Docs - Buliding and managing an extensive API for Robotics and loT
      link: https://docs.zorabots.be/dev-mqtt-docs/latest/index.html

- companyName: Walmart
  useCase: Managing a central API Hub for internal teams. Using AsyncAPI for events discoverability an visibility in a single place. AsyncAPI also enabled company-wide governance on asynchronous APIs.
  resources:
    - title: Video - Time For AsyncAPI Specification
      link: https://www.youtube.com/watch?v=SxTpGRaNIPo

- companyName: eBay
  useCase: Enabling partners to build with eBay through asynchronous communication. Public AsyncAPI documents enable code generation and faster integration. It also enables governance and standardisation.
  resources:
    - title: "Video - AsyncAPI 2.0: Enabling the Event-Driven World"
      link: https://www.youtube.com/watch?v=SxTpGRaNIPo
    - title: "Article - AsyncAPI 2.0: Enabling the Event-Driven World"
      link: https://innovation.ebayinc.com/tech/engineering/asyncapi-2-0-enabling-the-event-driven-world/
    - title: Docs - Overview of Notification API with public AsyncAPI documents
      link: https://developer.ebay.com/api-docs/commerce/notification/overview.html