# Centrally managed in asyncapi/.github repo
name: Lint PR title

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - if: >
          !contains(fromJson('["asyncapi-bot", "dependabot[bot]", "dependabot-preview[bot]", "allcontributors[bot]"]'), github.actor)
        uses: amannn/action-semantic-pull-request@v5.2.0
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" in the PR title "{title}" should start with a lowercase letter.

      - if: ${{ always() && steps.lint_pr_title.outputs.error_message != null }}
        name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          header: pr-title-lint-error
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          message: |
            We require all PRs to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        name: Delete PR title lint comment
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          header: pr-title-lint-error
          delete: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
