name: Slack Notifications

on:
  workflow_run:
    workflows: ['*']
    types: [completed]
    branches: [master]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "GitHub Action Workflow Status"
            unfurl_links: false
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "Workflow Status Update"
                  emoji: true
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Workflow:*\n<${{ github.event.workflow_run.html_url }}|${{ github.event.workflow_run.name }}>"
                  - type: mrkdwn
                    text: "*Status:*\n${{ github.event.workflow_run.conclusion }}"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*Branch:*\n<https://github.com/${{ github.repository }}/tree/${{ github.event.workflow_run.head_branch }}|${{ github.event.workflow_run.head_branch }}>"
                  - type: mrkdwn
                    text: "*Triggered by:*\n<${{ github.event.workflow_run.actor.html_url }}|${{ github.event.workflow_run.actor.login }}>"
              - type: actions
                elements:
                  - type: button
                    text:
                      type: plain_text
                      text: "View Workflow Run"
                      emoji: true
                    url: "${{ github.event.workflow_run.html_url }}"
