name: Slack Notifications

on:
  workflow_run:
    workflows: ['*']
    types: [completed]
    branches: [master]

jobs:
  slack-notifications:
    if: >
      github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.WEBSITE_SLACK_WEBHOOK }}
          SLACK_TITLE: 'Docs Edit Link Checker Errors Report'
          SLACK_MESSAGE: |
            🚨 The workflow <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow_run.name }}> failed on branch master.

            cc: @maintainers_website

          MSG_MINIMAL: true
