name: Tools preview on PR level

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  regenerateTools:
    if: github.repository == 'asyncapi/website'
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    name: Regenerate tools.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || '' }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Regenerate
        run: npm run generate:tools

      - name: Create Pull Request with new tools.json version
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore: update tools.json'
          committer: asyncapi-bot <info@asyncapi.io>
          author: asyncapi-bot <info@asyncapi.io>
          title: 'chore: update tools.json'
          branch: update-tools/${{ github.run_number }}
          base: ${{ github.head_ref }}
